---
- hosts: all
  roles:
  - role: modcloth.newrelic-haproxy-agent
    new_relic_license_key: "ABCD"
    newrelic_haproxy_agent_agents:
    - name: 'Foo'
      uri: 'www.example.com/stats;#csv'
      proxy: 'abcd'
      proxy_type: 'frontend'
